name: Python package

on: [push, pull_request]

jobs:
test:
runs-on: windows-latest
strategy:
matrix:
#python-version: ["3.9", "3.10", "3.11", "3.12"]

steps:
- uses: actions/checkout@v5

- name: Set up Python
uses: actions/setup-python@v5
with:
#python-version: ${{ matrix.python-version }}
python-version: '3.9'
#cache: 'pip'

- name: Install dependencies
run: |
#python -m pip install --upgrade pip
pip install -r requirements.txt

- name: Install playwright
run: |
python -m pip install playwright

- name: Install playwright library
run: |
python -m playwright install

- name: Install pytest-playwright
run: |
python -m pip install pytest-playwright

- name: Install requests
run: |
python -m pip install requests

- name: Run pytest
run: |
pip install pytest pytest-cov
pytest --doctest-modules \
--junitxml=junit/test-results-${{ matrix.python-version }}.xml \
--cov=. --cov-report=xml --cov-report=html

- name: Upload test results
if: ${{ always() }}
uses: actions/upload-artifact@v4
with:
name: pytest-results-${{ matrix.python-version }}
path: junit/test-results-${{ matrix.python-version }}.xml